name: build-and-push-image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "rodrigo/*"

env:
  ID_PROVIDER: projects/744310309265/locations/global/workloadIdentityPools/gha-oidc-pool/providers/gha-oidc-provider
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY: github
  REGION: us-east4
  REGISTRY: us-east4-docker.pkg.dev

jobs:
  build-image:
    strategy:
      matrix:
        project_id: [dev-j3tpk]

    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: ${{ matrix.project_id }}
      SERVICE_ACCOUNT: ext-gha-jetify-examples@${{ matrix.project_id }}.iam.gserviceaccount.com

    runs-on: ubuntu-latest
    steps:
      - name: Ensure prod is only deployed from main
        run: |-
          if [ ${PROJECT_ID} == "prod-j3tpk" ] && [ "${{ github.ref_name }}" != "main" ]; then
            echo "Cannot deploy to prod from non-main branch"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git credentials
        run: gh auth setup-git

      - name: Authenticate with GCP (via Workload Federation)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.ID_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          token_format: access_token

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache: false

      - name: Setup Ko
        uses: ko-build/setup-ko@v0.7

      - name: Login to Artifact Registry
        run: |-
          ko login "${{ env.REGISTRY }}" --username oauth2accesstoken --password "${{ steps.auth.outputs.access_token }}"

      - name: Build and Publish Image
        env:
          KO_DOCKER_REPO: "${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}"
        run: |-
          ko build -B . \
            --image-label "repository=${{ github.repository }}" \
            --image-label "revision=${{ github.sha }}" \
            --image-label "ref=${{ github.ref_name }}" \
            --image-label "workflow=${{ github.workflow_ref }}" \
            --tags "latest"
